version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/staq main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    lint-test:
        desc: Run the lint test before pushing code to GitHub
        cmds:
        - golangci-lint run